"""
Comprehensive vocabulary definitions for the dream coherence world.
Provides extensive lists of entities, types, and actions for data augmentation.
"""

from typing import Dict, List, Set

# Master dictionary of entity types and their member nouns
# Maps core_type -> list of specific names
ENTITY_VOCABULARY: Dict[str, List[str]] = {
    "animal": [
        "aardvark", "albatross", "alligator", "alpaca", "ant", "anteater", "antelope", "ape", "armadillo", "baboon",
        "badger", "bat", "bear", "beaver", "bee", "beetle", "bird", "bison", "boar", "buffalo", "bull", "butterfly",
        "camel", "capybara", "cat", "caterpillar", "cattle", "chamois", "cheetah", "chicken", "chimpanzee", "chinchilla",
        "clam", "cobra", "cockroach", "cod", "coyote", "crab", "crane", "crocodile", "crow", "deer", "dinosaur", "dog",
        "dolphin", "donkey", "dove", "dragonfly", "duck", "eagle", "echidna", "eel", "elephant", "elk", "emu", "falcon",
        "ferret", "finch", "fish", "flamingo", "fly", "fox", "frog", "gazelle", "gerbil", "giraffe", "gnat", "gnu",
        "goat", "goldfish", "goose", "gorilla", "grasshopper", "grouse", "guineapig", "gull", "hamster", "hare", "hawk",
        "hedgehog", "heron", "herring", "hippo", "hippopotamus", "hornet", "horse", "human", "hummingbird", "hyena",
        "ibex", "ibis", "iguana", "impala", "jackal", "jaguar", "jay", "jellyfish", "kangaroo", "kingfisher", "koala",
        "komododragon", "kookaburra", "kouprey", "kudu", "lapwing", "lark", "lemur", "leopard", "lion", "llama",
        "lobster", "locust", "loris", "louse", "lyrebird", "magpie", "mallard", "manatee", "mandrill", "mantis",
        "marten", "meerkat", "mink", "mole", "mongoose", "monkey", "moose", "mosquito", "mouse", "mule", "narwhal",
        "newt", "nightingale", "octopus", "okapi", "opossum", "oryx", "ostrich", "otter", "owl", "ox", "oyster",
        "panda", "panther", "parrot", "partridge", "peafowl", "pelican", "penguin", "pheasant", "pig", "pigeon",
        "pony", "porcupine", "porpoise", "quail", "quelea", "rabbit", "raccoon", "rail", "ram", "rat", "raven",
        "reddeer", "redpanda", "reindeer", "rhinoceros", "rook", "salamander", "salmon", "sanddollar", "sandpiper",
        "sardine", "scorpion", "seahorse", "seal", "shark", "sheep", "shrew", "skunk", "snail", "snake", "sparrow",
        "spider", "spoonbill", "squid", "squirrel", "starling", "stingray", "stinkbug", "stork", "swallow", "swan",
        "tapir", "tarsier", "termite", "tiger", "toad", "trout", "turkey", "turtle", "viper", "vulture", "wallaby",
        "walrus", "wasp", "weasel", "whale", "wildcat", "wolf", "wolverine", "wombat", "woodcock", "woodpecker", "worm",
        "wren", "yak", "zebra"
    ],
    "person": [
        "accountant", "actor", "actress", "admin", "agent", "ambassador", "analyst", "architect", "artist", "athlete",
        "author", "baker", "banker", "barber", "bard", "barista", "biologist", "blacksmith", "broker", "builder",
        "butcher", "captain", "carpenter", "chef", "chemist", "clerk", "coach", "coder", "commander", "composer",
        "cook", "counselor", "dancer", "dentist", "designer", "detective", "director", "doctor", "driver", "economist",
        "editor", "electrician", "engineer", "farmer", "firefighter", "fisherman", "florist", "gardener", "general",
        "geologist", "guard", "guide", "hunter", "inspector", "instructor", "intern", "investor", "janitor", "journalist",
        "judge", "lawyer", "librarian", "manager", "mechanic", "medic", "merchant", "miner", "model", "monk",
        "musician", "nurse", "officer", "painter", "paramedic", "pastor", "pharma", "pilot", "plumber", "poet",
        "police", "politician", "priest", "professor", "programmer", "psychologist", "publisher", "ranger", "recruiter",
        "reporter", "researcher", "sailor", "salesperson", "scholar", "scientist", "scout", "secretary", "security",
        "sheriff", "singer", "soldier", "spy", "student", "surgeon", "tailor", "teacher", "tech", "thief", "trader",
        "trainer", "translator", "trucker", "tutor", "vet", "waiter", "waitress", "warden", "warrior", "watchman",
        "welder", "writer", "wizard", "witch", "king", "queen", "prince", "princess"
    ],
    "place": [
        "airport", "apartment", "aquarium", "arcade", "archive", "arena", "attic", "bakery", "balcony", "bank",
        "barn", "barracks", "base", "basement", "bathroom", "beach", "bedroom", "bridge", "bunker", "cabin",
        "cafe", "cafeteria", "camp", "canyon", "castle", "cathedral", "cave", "cellar", "cemetery", "chapel",
        "church", "cinema", "city", "classroom", "cliff", "clinic", "cloud", "club", "college", "colony",
        "concert", "corner", "cottage", "court", "courtyard", "crater", "creek", "deck", "desert", "diner",
        "dock", "dorm", "dungeon", "factory", "farm", "field", "forest", "fort", "fountain", "gallery",
        "garage", "garden", "gate", "glacier", "gorge", "grocery", "gym", "hall", "hallway", "harbor",
        "haven", "hill", "hospital", "hotel", "house", "hut", "inn", "island", "jungle", "kitchen",
        "lab", "laboratory", "lake", "library", "lighthouse", "lobby", "lodge", "loft", "lounge", "mall",
        "mansion", "market", "meadow", "mess", "mine", "monument", "moon", "mosque", "motel", "mountain",
        "museum", "nest", "office", "orchard", "palace", "park", "patio", "pavilion", "peak", "pier",
        "plain", "planet", "plaza", "pond", "pool", "port", "prison", "pub", "pyramid", "ranch",
        "reef", "restaurant", "river", "road", "roof", "room", "ruin", "saloon", "sanctuary", "sand",
        "school", "sea", "shed", "shop", "shore", "shrine", "sky", "skyscraper", "stadium", "stage",
        "station", "store", "street", "studio", "subway", "swamp", "temple", "tent", "theater", "tomb",
        "tower", "town", "track", "trail", "tunnel", "university", "valley", "vault", "village", "volcano",
        "warehouse", "waterfall", "well", "wetland", "woods", "workshop", "yard", "zoo"
    ],
    "object": [
        "anchor", "anvil", "apple", "armor", "arrow", "axe", "backpack", "bag", "ball", "balloon",
        "banana", "barrel", "basket", "bat", "battery", "bed", "bell", "belt", "bench", "bike",
        "bin", "blanket", "board", "boat", "bolt", "bomb", "book", "bottle", "bowl", "box",
        "bracelet", "bread", "brick", "bridge", "broom", "brush", "bucket", "bulb", "bullet", "bus",
        "button", "cabinet", "cable", "cake", "calculator", "camera", "can", "candle", "canvas", "cap",
        "car", "card", "carpet", "cart", "case", "chain", "chair", "chalk", "cheese", "chest",
        "chip", "chisel", "clock", "cloth", "cloud", "coat", "coin", "comb", "compass", "computer",
        "cone", "console", "container", "cord", "cork", "couch", "crate", "crystal", "cup", "curtain",
        "cushion", "dagger", "dart", "deck", "desk", "diamond", "dice", "disk", "doll", "door",
        "drill", "drive", "drone", "drum", "dust", "egg", "engine", "envelope", "fan", "feather",
        "fence", "file", "film", "filter", "flag", "flashlight", "flask", "flower", "flute", "food",
        "fork", "frame", "fridge", "fruit", "fuel", "furnace", "fuse", "game", "garbage", "gate",
        "gear", "gem", "generator", "glass", "glove", "glue", "gold", "goggles", "grain", "grass",
        "grenade", "grid", "guitar", "gun", "hammer", "hat", "headphones", "helmet", "hoe", "hook",
        "horn", "hose", "ice", "icon", "ink", "iron", "jacket", "jar", "jewel", "key",
        "keyboard", "kite", "knife", "ladder", "lamp", "lantern", "laptop", "leaf", "lens", "letter",
        "lever", "light", "lock", "log", "machine", "magnet", "map", "mask", "mat", "match",
        "medal", "medicine", "metal", "mic", "microphone", "mirror", "missile", "model", "monitor", "moon",
        "motor", "mouse", "mug", "nail", "needle", "net", "note", "nut", "oar", "oil",
        "ore", "organ", "ornament", "oven", "pack", "package", "pad", "paddle", "paint", "pan",
        "panel", "paper", "parachute", "parcel", "pen", "pencil", "phone", "photo", "piano", "picture",
        "pie", "pill", "pillow", "pipe", "pistol", "pitchfork", "plane", "plank", "plant", "plate",
        "plug", "pocket", "pod", "pole", "pot", "potion", "powder", "prism", "pump", "purse",
        "puzzle", "radio", "raft", "rail", "rake", "ring", "robot", "rock", "rocket", "rod",
        "rope", "rug", "ruler", "sack", "saddle", "safe", "sail", "salt", "sand", "saw",
        "scale", "scarf", "screen", "screw", "scroll", "sculpture", "seat", "seed", "sensor", "server",
        "shaft", "shard", "sheet", "shelf", "shell", "shield", "ship", "shirt", "shoe", "shovel",
        "sign", "silk", "silver", "sink", "skate", "ski", "skull", "sled", "sledge", "slide",
        "soap", "sock", "socket", "soda", "sofa", "soil", "solar", "spacechip", "spade", "spear",
        "sphere", "spice", "spike", "spoon", "sponge", "spring", "stamp", "statue", "stick", "stone",
        "stool", "stove", "straw", "string", "structure", "suit", "sun", "sword", "table", "tablet",
        "tag", "tank", "tape", "target", "tarp", "tea", "telescope", "tent", "text", "thermometer",
        "thread", "ticket", "tile", "tire", "tissue", "toaster", "token", "tool", "torch", "totem",
        "towel", "tower", "toy", "track", "tractor", "train", "trap", "trash", "tray", "tree",
        "trophy", "truck", "tube", "turbine", "tv", "typewriter", "umbrella", "uniform", "urn", "valve",
        "vase", "vehicle", "veil", "vent", "vessel", "vest", "vial", "video", "violin", "visor",
        "wagon", "wall", "wallet", "wand", "watch", "water", "weapon", "web", "wheel", "whip",
        "whistle", "window", "wing", "wire", "wood", "wool", "wrench", "yarn"
    ]
}

# Attributes typically associated with types
TYPE_ATTRIBUTES: Dict[str, Dict[str, List[str]]] = {
    "animal": {
        "size": ["tiny", "small", "medium", "large", "huge", "gigantic"],
        "color": ["black", "white", "brown", "gray", "spotted", "striped", "golden", "red", "blue", "green"],
        "mood": ["calm", "hungry", "angry", "sleeping", "hunting", "scared", "playful", "happy"],
        "age": ["young", "adult", "old", "baby"],
        "speed": ["slow", "fast", "rapid", "sluggish"],
    },
    "person": {
        "age": ["child", "teen", "adult", "elderly", "20", "30", "40", "50", "60"],
        "mood": ["happy", "sad", "angry", "bored", "busy", "tired", "excited", "nervous"],
        "role": ["leader", "follower", "novice", "expert", "master"],
        "status": ["wealthy", "poor", "famous", "unknown"],
    },
    "place": {
        "size": ["small", "cramped", "medium", "spacious", "vast", "endless"],
        "atmosphere": ["dark", "bright", "foggy", "clear", "gloomy", "cheerful", "eerie"],
        "temperature": ["freezing", "cold", "cool", "warm", "hot", "scorching"],
        "condition": ["ruined", "new", "ancient", "clean", "dirty", "pristine"],
    },
    "object": {
        "weight": ["light", "heavy", "massive"],
        "condition": ["broken", "working", "new", "old", "rusty", "shiny"],
        "material": ["wood", "metal", "plastic", "glass", "stone", "cloth"],
        "color": ["red", "blue", "green", "yellow", "black", "white", "silver", "gold"],
        "value": ["cheap", "expensive", "priceless", "worthless"],
    }
}

# Verbs/Actions schema
# verb -> {valid_actors: [], valid_targets: []}
ACTION_VOCABULARY = [
    {"verb": "observes", "valid_actors": ["animal", "person"], "valid_targets": ["animal", "object", "place", "person"]},
    {"verb": "examines", "valid_actors": ["person"], "valid_targets": ["object", "animal", "place", "person"]},
    {"verb": "chases", "valid_actors": ["animal", "person"], "valid_targets": ["animal", "person"]},
    {"verb": "flees_from", "valid_actors": ["animal", "person"], "valid_targets": ["animal", "person", "object"]},
    {"verb": "eats", "valid_actors": ["animal", "person"], "valid_targets": ["object", "animal"]},
    {"verb": "drinks", "valid_actors": ["animal", "person"], "valid_targets": ["object"]},
    {"verb": "holds", "valid_actors": ["person"], "valid_targets": ["object", "animal"]},
    {"verb": "drops", "valid_actors": ["person", "animal"], "valid_targets": ["object"]},
    {"verb": "throws", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "pushes", "valid_actors": ["person", "animal"], "valid_targets": ["object", "person", "animal"]},
    {"verb": "pulls", "valid_actors": ["person", "animal"], "valid_targets": ["object", "person", "animal"]},
    {"verb": "opens", "valid_actors": ["person"], "valid_targets": ["object", "place"]},
    {"verb": "closes", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "locks", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "unlocks", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "climbs", "valid_actors": ["person", "animal"], "valid_targets": ["object", "place"]},
    {"verb": "jumps_over", "valid_actors": ["person", "animal"], "valid_targets": ["object"]},
    {"verb": "walks_to", "valid_actors": ["person", "animal"], "valid_targets": ["place", "object", "person"]},
    {"verb": "runs_to", "valid_actors": ["person", "animal"], "valid_targets": ["place", "object", "person"]},
    {"verb": "flies_to", "valid_actors": ["animal"], "valid_targets": ["place", "object"]},  # Simplified: assumes animal can fly
    {"verb": "speaks_to", "valid_actors": ["person"], "valid_targets": ["person"]},
    {"verb": "listens_to", "valid_actors": ["person"], "valid_targets": ["person", "object", "animal"]},
    {"verb": "attacks", "valid_actors": ["person", "animal"], "valid_targets": ["person", "animal"]},
    {"verb": "defends", "valid_actors": ["person", "animal"], "valid_targets": ["person", "animal", "place"]},
    {"verb": "builds", "valid_actors": ["person"], "valid_targets": ["object", "place"]},
    {"verb": "destroys", "valid_actors": ["person", "animal"], "valid_targets": ["object"]},
    {"verb": "repairs", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "buys", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "sells", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "steals", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "finds", "valid_actors": ["person", "animal"], "valid_targets": ["object", "place", "animal"]},
    {"verb": "loses", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "hides", "valid_actors": ["person", "animal"], "valid_targets": ["object"]},
    {"verb": "seeks", "valid_actors": ["person", "animal"], "valid_targets": ["object", "person", "animal"]},
    {"verb": "greets", "valid_actors": ["person"], "valid_targets": ["person"]},
    {"verb": "insults", "valid_actors": ["person"], "valid_targets": ["person"]},
    {"verb": "helps", "valid_actors": ["person"], "valid_targets": ["person", "animal"]},
    {"verb": "hinders", "valid_actors": ["person"], "valid_targets": ["person"]},
    {"verb": "teaches", "valid_actors": ["person"], "valid_targets": ["person"]},
    {"verb": "learns_from", "valid_actors": ["person"], "valid_targets": ["person", "object"]},
    {"verb": "reads", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "writes", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "paints", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "cooks", "valid_actors": ["person"], "valid_targets": ["object"]},
    {"verb": "cleans", "valid_actors": ["person"], "valid_targets": ["object", "place"]},
    {"verb": "drives", "valid_actors": ["person"], "valid_targets": ["object"]},  # Vehicle is object
    {"verb": "rides", "valid_actors": ["person"], "valid_targets": ["animal", "object"]},
    {"verb": "enters", "valid_actors": ["person", "animal"], "valid_targets": ["place", "object"]},
    {"verb": "exits", "valid_actors": ["person", "animal"], "valid_targets": ["place"]},
    {"verb": "sleeps_in", "valid_actors": ["person", "animal"], "valid_targets": ["place", "object"]},
]
